# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' stats allele frequency
#'  
#' stats allele frequency of character genotypes vector 
#'
#' @param vector a character vector of genotypes
#' @param sep the separator for character genotypes(i.e., "" ,"/", "|")
#' 
#' @return list
#' @export
#' @name stats_freq
#' @rdname stats_freq
#' @examples
#' 
#' g0 <- c('T/A', NA, 'T|T', NA, 'T|A', NA, 'T|T', 'T/A','T/T', 'T/T', 
#'         'T/A', 'A|A', 'T/T', 'T|A', 'T/A', 'T|T', NA, 'T|A', 'T/A', NA)
#' 
#' stats_freq(g0, "/|")
NULL

#' Convert character genotype to integer genotype
#' 
#' convert genotypes separated by ("", "/", "|", ...) to integer genotypes(0, 1, 2, NA, NA for missing value)
#'
#' @param vector a character vector of genotypes
#' @param sep the separator for character genotypes(i.e., "" ,"/", "|")
#' 
#' @name recode
#' @rdname recode
#' @export
#' @examples
#' 
#' g0 <- c('T/A', NA, 'T|T', NA, 'T|A', NA, 'T|T', 'T/A','T/T', 'T/T', 
#'         'T/A', 'A|A', 'T/T', 'T|A', 'T/A', 'T|T', NA, 'T|A', 'T/A', NA)
#'         
#' code012_g1 <- recode(g0, "/|")
#' 
#' g1 <- c('T/A', NA, 'T/T', NA, 'T/A', NA, 'T/T', 'T/A','T/T', 'T/T', 
#'         'T/A', 'A/A', 'T/T', 'T/A', 'T/A', 'T/T', NA, 'T/A', 'T/A', NA)  
#' 
#' code012_g1 <- recode(g1, "/")
#' 
#' g2 <- c('01', '01', '00', '01', '00', '01', '01', '01', '01', '00', 
#'         '01', '11', '01', '11', '01', '11','01', '01', '01', '11') 
#'         
#' code012_g2 <- recode(g2, "")
NULL

stats_freq <- function(vector, sep) {
    .Call(`_GWLD_stats_freq`, vector, sep)
}

recode <- function(vector, sep) {
    .Call(`_GWLD_recode`, vector, sep)
}

code_Mat <- function(Matrix, sep) {
    .Call(`_GWLD_code_Mat`, Matrix, sep)
}

read_bed <- function(bedfile, nSample) {
    .Call(`_GWLD_read_bed`, bedfile, nSample)
}

read_vcf <- function(filename, genotype) {
    .Call(`_GWLD_read_vcf`, filename, genotype)
}

RMIC <- function(g1, g2) {
    .Call(`_GWLD_RMIC`, g1, g2)
}

RMIC_Mat <- function(geno012, cores = 1L) {
    .Call(`_GWLD_RMIC_Mat`, geno012, cores)
}

MIC <- function(g1, g2) {
    .Call(`_GWLD_MIC`, g1, g2)
}

MIC_Mat <- function(geno012, cores = 1L) {
    .Call(`_GWLD_MIC_Mat`, geno012, cores)
}

LDC <- function(g1, g2, method = "r^2") {
    .Call(`_GWLD_LDC`, g1, g2, method)
}

LDC_Mat <- function(geno012, method, cores = 1L) {
    .Call(`_GWLD_LDC_Mat`, geno012, method, cores)
}

gwld <- function(geno012, method = "RMI", thread = 1L) {
    .Call(`_GWLD_gwld`, geno012, method, thread)
}

decay <- function(m, snpinfo, maxdist = 300L) {
    .Call(`_GWLD_decay`, m, snpinfo, maxdist)
}

calc_decay <- function(geno012, snpinfo, method = "RMI", thread = 1L, maxdist = 300L) {
    .Call(`_GWLD_calc_decay`, geno012, snpinfo, method, thread, maxdist)
}

calc_circos <- function(geno012, snpinfo, method = "RMI", thread = 1L, threshold = 0.2) {
    .Call(`_GWLD_calc_circos`, geno012, snpinfo, method, thread, threshold)
}

circos <- function(m, snpinfo, threshold = 0.2) {
    .Call(`_GWLD_circos`, m, snpinfo, threshold)
}

